name: Tools
version: 1.0
main: com.gmail.alexwazzan1.tools.Main

commands:
  set:
    description: Set dimensions.
  reset:
    description: Reset dimensions.
  undo:
    description: Undo.
  copy:
    description: Copy.